export type Settings={minInterval:number;maxInterval:number;errorWeight:number;successWeight:number;dailyCapacity:number;questionsPerReview:number;examDate:string};
export type Topic={id:string;area:string;theme:string;subtheme:string;attempts:number;correct:number;streak:number;ease:number;interval:number;lastReview:string;nextReview:string;recent:number[];note?:string};
export const defaults:Settings={minInterval:1,maxInterval:90,errorWeight:1.35,successWeight:1,dailyCapacity:15,questionsPerReview:8,examDate:"2026-11-15"};
const day=(d:string,n:number)=>{const x=new Date(d+"T12:00:00");x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
export function score(t:Topic,today=new Date().toISOString().slice(0,10)){const n=t.attempts,errors=n-t.correct,bayes=(errors+2)/(n+4),recent=t.recent.length?1-t.recent.reduce((a,b)=>a+b,0)/t.recent.length:.5,overdue=Math.max(0,(+new Date(today)-+new Date(t.nextReview))/864e5),uncertainty=1/Math.sqrt(n+1),negativeStreak=Math.max(0,-t.streak);return Math.round(clamp((.38*bayes+.25*recent+.14*uncertainty+.13*Math.min(overdue/7,1)+.1*Math.min(negativeStreak/3,1))*100,0,100));}
export function priority(s:number){return s>=58?"Alta":s>=34?"Média":"Baixa"}
export function updateTopic(t:Topic,total:number,correct:number,date:string,s:Settings=defaults):Topic{const rate=total?correct/total:0,passed=rate>=.7;const streak=passed?Math.max(0,t.streak)+1:Math.min(0,t.streak)-1;const ease=clamp(t.ease+(rate-.7)*.32-(passed?0:.12*s.errorWeight),1.25,2.8);let interval:number;if(!passed)interval=rate<.5?s.minInterval:Math.min(3,Math.max(s.minInterval,2));else if(streak===1)interval=rate>=.9?5:3;else interval=Math.round(Math.max(3,t.interval)*ease*(.82+.28*rate)*s.successWeight);interval=clamp(interval,s.minInterval,s.maxInterval);if(s.examDate){const until=Math.floor((+new Date(s.examDate)-+new Date(date))/864e5);if(until>=0)interval=Math.min(interval,Math.max(s.minInterval,until));}return {...t,attempts:t.attempts+total,correct:t.correct+correct,streak,ease,interval,lastReview:date,nextReview:day(date,interval),recent:[...t.recent,rate].slice(-5)};}
export function explain(t:Topic,today:string){const rate=t.attempts?Math.round(t.correct/t.attempts*100):0,recentErrors=t.recent.filter(x=>x<.7).length,since=Math.max(0,Math.round((+new Date(today)-+new Date(t.lastReview))/864e5));return `${t.subtheme||t.theme} foi programado porque sua taxa acumulada é ${rate}%, houve ${recentErrors} desempenho(s) recente(s) abaixo de 70% e a última revisão ocorreu há ${since} dia(s).`;}
export function distribute(topics:Topic[],s:Settings){const used:Record<string,number>={};return [...topics].sort((a,b)=>score(b)-score(a)).map(t=>{let d=t.nextReview;while((used[d]||0)>=s.dailyCapacity&&(!s.examDate||d<s.examDate))d=day(d,1);used[d]=(used[d]||0)+1;return {...t,nextReview:d}})}
